import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner/banner.component";
import NavBar from "../components/nav/navbar.component";
import SectionCards from "../components/card/sectionCards.component";
import { getVideos, getPopularVideos } from "../lib/videos";

export async function getServerSideProps() {
  const disneyVideos = await getVideos("disney trailers");
  const productivityVideos = await getVideos("productivity");
  const travelVideos = await getVideos("travel");
  const popularVideos = await getPopularVideos();
  return {
    props: { disneyVideos, productivityVideos, travelVideos, popularVideos },
  };
}

export default function Home(props) {
  const { disneyVideos, travelVideos, productivityVideos, popularVideos } =
    props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix Clone with Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar userName="Guess" />
        <Banner
          videoId="4zH5iYM4wJo"
          title="Cliffeord the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/clifford.jpg"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney " videos={disneyVideos} size="large" />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </main>
    </div>
  );
}
